In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
2+3

In [ ]:
6/3

In [ ]:
(3+8)/(2*3)

In [ ]:
(3*8)/(2*3)

In [ ]:
log(12)

In [ ]:
sqrt(121)

In [ ]:
x <- 1:10
cat(x)
cat('Mean of x is',mean(x)) # cat and print , both can be used for printing
cat('Median of x is',median(x)) # if we are using cat all outputs will be concatenated
cat('Variance of x is',var(x))
cat('Standard deviation of x is',sd(x))

In [ ]:
cat(x,'\n')
cat('Mean of x is',mean(x),'\n') # cat and print , both can be used for printing
cat('Median of x is',median(x),'\n') # if we are using cat all outputs will be concatenated
cat('Variance of x is',var(x),'\n')
cat('Standard deviation of x is',sd(x),'\n')

In [ ]:
print(x)
print(paste('Mean of x is',mean(x)))
print(paste('Median of x is',median(x)))
print(paste('variance of x is',var(x)))
print(paste('Standard deviation of x is',sd(x)))

In [ ]:
x <- 8+7
x

In [ ]:
#character variable creation
x<-"dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#numerical variable creation
x<-23
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#integer vriable creation
x<-23L
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#complex variable creation
x<-2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#logical variable creation
x<-TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
vector()#an empty 'logical' (the default) vector

In [ ]:
vector("character",length = 5)#a vector of mode 'character' with 5 elements

In [ ]:
character(5) # the same thing but using the constructor directly

In [ ]:
numeric(5) #a numeric vector with 5 elements

In [ ]:
logical(5) # a logical vector with 5 elements

In [33]:
# numeric vector having 5 elements
x<-c(12,24,36,48,60)

In [34]:
x
class(x)

[1] 12 24 36 48 60

[1] "numeric"

In [36]:
# integer vector having 5 elements
x<-c(12L,24L,36L,48L,60L,72L)
x
class(x)
length(x)

[1] 12 24 36 48 60 72

[1] "integer"

[1] 6

In [37]:
#logical vector having 5 elements
y<-c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [38]:
#character vector having 3 elements
z<-c("Abhi","yash","chitti")
z
class(z)
length(z)

[1] "Abhi"   "yash"   "chitti"

[1] "character"

[1] 3

In [39]:
#add element at an end
print("elements in z before")
z
z<-c(z,"abhinav")
print("elements in z after adding new element")
z

[1] "elements in z before"


[1] "Abhi"   "yash"   "chitti"

[1] "elements in z after adding new element"


[1] "Abhi"    "yash"    "chitti"  "abhinav"

In [40]:
#add an element at the front
print("elements in z before")
z
z<-c("batchu",z)
print("elements in z after adding new element")
z

[1] "elements in z before"


[1] "Abhi"    "yash"    "chitti"  "abhinav"

[1] "elements in z after adding new element"


[1] "batchu"  "Abhi"    "yash"    "chitti"  "abhinav"

In [41]:
a<-1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [43]:
seq(05)

[1] 1 2 3 4 5

In [44]:
seq(from=1,to=10,by=0.2)

[1]  1.0  1.2  1.4  1.6  1.8  2.0  2.2  2.4  2.6  2.8  3.0  3.2  3.4  3.6  3.8
[16]  4.0  4.2  4.4  4.6  4.8  5.0  5.2  5.4  5.6  5.8  6.0  6.2  6.4  6.6  6.8
[31]  7.0  7.2  7.4  7.6  7.8  8.0  8.2  8.4  8.6  8.8  9.0  9.2  9.4  9.6  9.8
[46] 10.0

In [45]:
1/0

[1] Inf

In [46]:
0/0

[1] NaN

In [47]:
exp(Inf) # e raised to the power infinity is infinity

[1] Inf

In [48]:
exp(-Inf)

[1] 0

In [49]:
Inf-Inf

[1] NaN

In [50]:
log(0)

[1] -Inf

In [51]:
log(1)

[1] 0

In [52]:
a<-c(1.7,"a")
a

[1] "1.7" "a"

In [53]:
b<-c(TRUE,2,3,FALSE)#TRUE is converted to 1 and FALSE will be converted to zero
b

[1] 1 2 3 0

In [54]:
c<-c("a",TRUE)#all logical values will be converted to character
c

[1] "a"    "TRUE"

In [55]:
as.numeric("1")#conversion from character to numeric

[1] 1

In [56]:
as.numeric(c("45","66"))

[1] 45 66

In [58]:
as.numeric(c("45","66","six"))#invalid conversion . Missing values will be introduced

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [59]:
as.character(22)#conversion from numeric to characrter

[1] "22"

In [61]:
as.character(c(22,34,56))#conversion from numeric to characrter

[1] "22" "34" "56"

In [62]:
#Example-1
m<-matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [63]:
dim(m)

[1] 2 2

In [64]:
class(m)

[1] "matrix"

In [65]:
typeof(m)

[1] "logical"

In [66]:
#Example-2
m<-matrix(c(1:3))
print('Given matrix is')
print(m)
print('dimensions (size) of Given matrix is')
print(dim(m))
print('class of Given matrix is')
print(class(m))
print('type of Given matrix is')
print(typeof(m))

[1] "Given matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "dimensions (size) of Given matrix is"
[1] 3 1
[1] "class of Given matrix is"
[1] "matrix"
[1] "type of Given matrix is"
[1] "integer"


In [67]:
a<-matrix(1:6,nrow=2,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [68]:
m<-1:10 #creation of a matrix m. Dimensions of  matrix are not specified
print(m)# print the matrix
print(dim(m))#print the dimensions
dim(m)<-c(2,5)#change the dimensions
print(m)#print the matrix
print(dim(m))#print the dimensions

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [69]:
my_name<- readline(prompt="enter name: ")
my_age<- readline(prompt="enter age: ")
#convert character into integer
my_age<- as.integer(my_age)
print(paste("hi,",my_name,"next year you will be",my_age+1,"years old."))

enter name: abhiram
enter age: 19
[1] "hi, abhiram next year you will be 20 years old."


In [70]:
w<- readline()
w

yash is hero


[1] "yash is hero"